server:
  port: 64412

spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: dev #
#  rabbitmq:
#    host: localhost
#    port: 15672
#    username: guest
#    password: guest

eureka:
  instance:
    instance-id: user-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, beans, bus-refresh, refresh
